-- 0001_initial_schema.sql

-- 1. Profiles Table
-- Stores public user data. Links to auth.users.
create table public.profiles (
  id uuid not null primary key references auth.users on delete cascade,
  username text unique,
  avatar_url text,
  updated_at timestamptz,

  constraint username_length check (char_length(username) >= 3)
);

-- Row Level Security for profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

-- Trigger to create a profile when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Cookbooks Table
create table public.cookbooks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  title text not null,
  author text,
  cover_image_url text,
  created_at timestamptz not null default now()
);

-- Row Level Security for cookbooks
alter table public.cookbooks enable row level security;
create policy "Users can view their own cookbooks." on public.cookbooks for select using (auth.uid() = user_id);
create policy "Users can insert their own cookbooks." on public.cookbooks for insert with check (auth.uid() = user_id);
create policy "Users can update their own cookbooks." on public.cookbooks for update using (auth.uid() = user_id);
create policy "Users can delete their own cookbooks." on public.cookbooks for delete using (auth.uid() = user_id);


-- 3. Recipes Table
create table public.recipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  cookbook_id bigint references public.cookbooks on delete set null,
  title text not null,
  duration_minutes integer,
  rating smallint,
  notes text,
  created_at timestamptz not null default now(),

  constraint rating_check check (rating >= 1 and rating <= 5)
);

-- Row Level Security for recipes
alter table public.recipes enable row level security;
create policy "Users can manage their own recipes." on public.recipes for all using (auth.uid() = user_id);
-- A policy for shared recipes will be added later.


-- 4. Ingredients Table
create table public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

-- Row Level Security for ingredients
alter table public.ingredients enable row level security;
create policy "Authenticated users can view all ingredients." on public.ingredients for select using (auth.role() = 'authenticated');
create policy "Authenticated users can insert new ingredients." on public.ingredients for insert with check (auth.role() = 'authenticated');
-- Note: Deleting/Updating ingredients might be an admin-only task in the future.


-- 5. Recipe-Ingredients Junction Table
create table public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes on delete cascade,
  ingredient_id bigint not null references public.ingredients on delete cascade,
  amount numeric,
  unit text,

  unique(recipe_id, ingredient_id)
);

-- Row Level Security for recipe_ingredients
alter table public.recipe_ingredients enable row level security;
create policy "Users can manage ingredients for their own recipes." on public.recipe_ingredients for all
  using (exists (select 1 from public.recipes where recipes.id = recipe_id and recipes.user_id = auth.uid()));


-- 6. Recipe Ratings Table
create table public.recipe_ratings (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes on delete cascade,
  user_id uuid not null references auth.users on delete cascade,
  likes_it boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz,

  unique(recipe_id, user_id)
);

-- Row Level Security for recipe_ratings
alter table public.recipe_ratings enable row level security;
create policy "Users can manage their own ratings." on public.recipe_ratings for all using (auth.uid() = user_id);
create policy "Users can view ratings for recipes they have access to." on public.recipe_ratings for select
  using (exists (select 1 from public.recipes where recipes.id = recipe_id)); -- This needs to be refined with sharing policies


-- 7. Recipe Shares Table
create table public.recipe_shares (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes on delete cascade,
  shared_by_user_id uuid not null references auth.users on delete cascade,
  shared_with_user_id uuid not null references auth.users on delete cascade,
  can_edit boolean not null default false,
  created_at timestamptz not null default now(),

  unique(recipe_id, shared_with_user_id)
);

-- Row Level Security for recipe_shares
alter table public.recipe_shares enable row level security;
create policy "Users can manage shares for their own recipes." on public.recipe_shares for all
  using (exists (select 1 from public.recipes where recipes.id = recipe_id and recipes.user_id = auth.uid()));
create policy "Users can view shares they have received." on public.recipe_shares for select
  using (auth.uid() = shared_with_user_id);

-- Now, update the recipe RLS to include shared recipes.
drop policy "Users can manage their own recipes." on public.recipes;

create policy "Users can view their own recipes." on public.recipes for select
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.recipe_shares
      where recipe_shares.recipe_id = recipes.id and recipe_shares.shared_with_user_id = auth.uid()
    )
  );

create policy "Users can insert their own recipes." on public.recipes for insert
  with check (user_id = auth.uid());

create policy "Users can update their own recipes or shared recipes with edit rights." on public.recipes for update
  using (
    user_id = auth.uid() or
    exists (
      select 1 from public.recipe_shares
      where recipe_shares.recipe_id = recipes.id and recipe_shares.shared_with_user_id = auth.uid() and recipe_shares.can_edit = true
    )
  );

create policy "Users can delete their own recipes." on public.recipes for delete
  using (user_id = auth.uid());